# 09. 교내 가로수 데이터 추가

## 1) import

In [1]:
import pandas as pd
import folium

## 2) 공간 데이터

In [49]:
file_path = "../artifacts/교내_가로수_정보.csv"
df = pd.read_csv(file_path)

print(f"데이터의 행과 열 개수: {df.shape}")
display(df.head())

데이터의 행과 열 개수: (1195, 5)

  memo  ID        lat         lng  type
0  A11   1  35.892483  128.609282     1
1  NaN   2  35.892553  128.609361     1
2  NaN   3  35.892623  128.609440     1
3  NaN   4  35.892693  128.609519     1
4  NaN   5  35.892763  128.609598     1

## 3) 교내 가로수 위치 표시

In [ ]:
file_path = "../artifacts/교내_가로수_정보.csv"
output_path = "../artifacts/campus_tree_map.html"

# csv 파일 읽기
df = pd.read_csv(file_path)
df.dropna(subset=['lat', 'lng'], inplace=True)

# 지도 생성
m = folium.Map(location=[df['lat'].mean(), df['lng'].mean()], zoom_start=16)

# 좌표마다 마커
for idx, row in df.iterrows():
    folium.CircleMarker(
        location=[row['lat'], row['lng']],
        radius=3,
        color='green',
        fill=True,
        popup=f"{row.get('memo', '')} - {row.get('ID', '')}"
    ).add_to(m)

m.save(output_path)
print("../artifacts/campus_tree_map.html에서 확인 가능")

../artifacts/campus_tree_map.html에서 확인 가능

## 4) 속성 데이터

In [50]:
file_path = "../artifacts/수종_정보.csv"
df = pd.read_csv(file_path)
    
print(f"데이터의 행과 열 개수: {df.shape}")
display(df.head())

데이터의 행과 열 개수: (7, 6)

  tree_name  type  heit  area  radius  gap
0      은행나무     1    15    40       4   10
1      왕벚나무     2    15    15       3    7
2     플라타너스     3    25   100       9   15
3      느티나무     4    18    40       5    7
4    히말라야시다     5    20    70       5   10

## 5) 공간 데이터 + 속성 데이터 병합

In [46]:
def load_and_merge_tree_data():
 
    tree_loc_path = "../artifacts/교내_가로수_정보.csv"
    tree_spec_path = "../artifacts/수종_정보.csv"

    trees_df = pd.read_csv(tree_loc_path)
    species_df = pd.read_csv(tree_spec_path)

    merged_df = pd.merge(trees_df, species_df, on='type', how='left')

    return merged_df

load_and_merge_tree_data()

,memo,ID,lat,lng,type,tree_name,heit,area,radius,gap
0,A11,1,35.892483,128.609282,1,은행나무,15,40,4,10
1,NaN,2,35.892553,128.609361,1,은행나무,15,40,4,10
2,NaN,3,35.892623,128.609440,1,은행나무,15,40,4,10
3,NaN,4,35.892693,128.609519,1,은행나무,15,40,4,10
4,NaN,5,35.892763,128.609598,1,은행나무,15,40,4,10
...,...,...,...,...,...,...,...,...,...,...
1190,NaN,1191,35.888898,128.611727,7,대왕참나무,25,70,7,10
1191,NaN,1192,35.888867,128.611703,7,대왕참나무,25,70,7,10
1192,NaN,1193,35.888836,128.611679,7,대왕참나무,25,70,7,10
1193,NaN,1194,35.888785,128.611638,7,대왕참나무,25,70,7,10
1194,NaN,1195,35.888718,128.611593,7,대왕참나무,25,70,7,10